# Site settings
title: data, code, and everything else in between
tagline:      Technical blog
baseurl:      ""
paginate:     1
email: tr.stringer@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Posts about all things code (C#, .NET, ASP.NET, node.js, JavaScript, git) 
  and data (SQL Server, MongoDB), and even a few non-tech things mixed in.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tstringer.github.io" # the base hostname & protocol for your site
twitter_username: tr_stringer
github_username:  tstringer

author:
  name:       Thomas Stringer
  url:        http://tstringer.github.io

# Build settings
gems:
  - jekyll-paginate

#Others
markdown: kramdown
